// Shared Excel builder for the calculator tools (SheetJS). The point is a
// LIVE model: projection cells are real formulas referencing the Inputs
// sheet and prior rows, so editing an assumption recalculates everything.
// (Community SheetJS can't write bold/frozen styling; formats + formulas do.)
import * as XLSX from "xlsx";

export const GBP = '£#,##0'; // number format for currency cells
export const PCT = '0.0"%"';

/** A cell: literal, or { f } formula, optionally with a number format z.
 *  Formula cells MUST carry their computed value in v — SheetJS community
 *  silently drops formula cells without a cached value. */
export type Cell =
  | string
  | number
  | { f: string; v: number | string; z?: string }
  | { v: number | string; z: string };

export interface Sheet {
  name: string; // ≤ 31 chars, Excel rule
  rows: Cell[][];
  colWidths?: number[]; // characters
}

export const FOOTER =
  "Generated by Churchill & Lincoln · manyuseful.tools · not financial advice";

/** Build an .xlsx as bytes from sheets of cells. Appends the footer note
 *  two rows under each sheet's content. */
export function buildXlsx(sheets: Sheet[]): Uint8Array {
  const wb = XLSX.utils.book_new();
  for (const s of sheets) {
    const aoa = [...s.rows, [], [FOOTER]];
    const ws = XLSX.utils.aoa_to_sheet([[]]);
    aoa.forEach((row, r) =>
      row.forEach((cell, c) => {
        const ref = XLSX.utils.encode_cell({ r, c });
        if (cell === null || cell === undefined) return;
        if (typeof cell === "object" && "f" in cell) {
          ws[ref] = {
            t: typeof cell.v === "number" ? "n" : "s",
            v: cell.v,
            f: cell.f,
            z: cell.z,
          };
        } else if (typeof cell === "object") {
          ws[ref] = { t: typeof cell.v === "number" ? "n" : "s", v: cell.v, z: cell.z };
        } else {
          ws[ref] = { t: typeof cell === "number" ? "n" : "s", v: cell };
        }
      }),
    );
    ws["!ref"] = XLSX.utils.encode_range(
      { r: 0, c: 0 },
      { r: aoa.length - 1, c: Math.max(...aoa.map((r) => r.length), 1) - 1 },
    );
    if (s.colWidths) ws["!cols"] = s.colWidths.map((wch) => ({ wch }));
    XLSX.utils.book_append_sheet(wb, ws, s.name);
  }
  const out = XLSX.write(wb, { type: "array", bookType: "xlsx" }) as ArrayBuffer;
  return new Uint8Array(out);
}

/** A1-style ref helper: cellRef(0, 1) → "B1" (row/col 0-indexed). */
export const cellRef = (r: number, c: number): string =>
  XLSX.utils.encode_cell({ r, c });
